name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    - name: Install Tesseract
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr
    - name: Download NLTK data
      run: |
        python -m nltk.downloader stopwords
        python -m nltk.downloader punkt
        python -m nltk.downloader punkt_tab
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint src
    - name: Test with pytest
      run: |
        pytest --cov=src --cov-report=xml
